/* automatically generated by rust-bindgen */

pub const HW_BREAKPOINT_LEN_1: ::libc::c_uint = 1;
pub const HW_BREAKPOINT_LEN_2: ::libc::c_uint = 2;
pub const HW_BREAKPOINT_LEN_4: ::libc::c_uint = 4;
pub const HW_BREAKPOINT_LEN_8: ::libc::c_uint = 8;

pub const HW_BREAKPOINT_EMPTY: ::libc::c_uint = 0;
pub const HW_BREAKPOINT_R: ::libc::c_uint = 1;
pub const HW_BREAKPOINT_W: ::libc::c_uint = 2;
pub const HW_BREAKPOINT_RW: ::libc::c_uint = 3;
pub const HW_BREAKPOINT_X: ::libc::c_uint = 4;
pub const HW_BREAKPOINT_INVALID: ::libc::c_uint = 7;

pub const TYPE_INST: ::libc::c_uint = 0;
pub const TYPE_DATA: ::libc::c_uint = 1;
pub const TYPE_MAX: ::libc::c_uint = 2;
